### POST authenticate user
POST {{hostname}}/login
Content-Type: application/json

{
  "username": "decima",
  "password": "password"
}

> {%
    client.global.set("token", response.body.result.token)
    client.global.set("refresh_token", response.body.result.refresh_token)
%}

### POST refresh token
POST {{hostname}}/login/refresh
Content-Type: application/json

{
  "refresh_token": "{{refresh_token}}"
}

> {%
    client.global.set("token", response.body.result.token)
    client.global.set("refresh_token", response.body.result.refresh_token)
%}

### GET fetch user details
GET {{hostname}}/whoami
Authorization: Bearer {{token}}

